/* =============================================================================
 *  bridge.c  --  Wires the //export'd Go functions into a dg_callbacks struct.
 * -----------------------------------------------------------------------------
 *  This tiny C file exists only because cgo forbids C *definitions* in the
 *  preamble of a file that uses //export. So the one place that references the
 *  exported Go symbols (goDGInit, ...) and builds the callback struct lives
 *  here. "_cgo_export.h" is generated by cgo and declares those Go functions.
 *  GPLv2. See LICENSE.
 * ===========================================================================*/

#include "doomgeneric_capi.h"
#include "_cgo_export.h"

void registerGoCallbacks(void)
{
    dg_callbacks cb;
    cb.init             = goDGInit;
    cb.draw_frame       = goDGDrawFrame;
    cb.sleep_ms         = goDGSleepMs;
    cb.get_ticks_ms     = goDGGetTicksMs;
    cb.get_key          = goDGGetKey;
    cb.set_window_title = goDGSetWindowTitle;
    dg_set_callbacks(&cb);
}
